FROM python:3.10-slim

WORKDIR /app

RUN apt-get update && apt-get install -y python3-dev libjpeg-dev zlib1g-dev \
    && apt-get clean

COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["python", "xenv/xvideos_channel.py"]
